GET http://localhost:9999/posts

###

DELETE http://localhost:9999/posts/1

###

POST http://localhost:9999/posts
Content-Type: application/json

{
    "content": "last post"
}

###
POST http://localhost:9999/posts/2/like
###
